/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.xjjc.accsubjmap;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-04-26 15:13:53
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class SubjMapVO extends SuperVO {
	private java.lang.String pk_subjmap;
	private java.lang.String pk_subjbiz;
	private java.lang.String pk_corp;
	private java.lang.String vothercode;
	private java.lang.String vothername;
	private java.lang.String votherbiz;
	private java.lang.String pk_debitsubj;
	private java.lang.String pk_creditsubj;
	private nc.vo.pub.lang.UFBoolean bmergesame;
	private java.lang.String vmemo;
	private java.lang.Integer obj_id;
	private java.lang.String currency;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_SUBJMAP = "pk_subjmap";
	public static final String PK_SUBJBIZ = "pk_subjbiz";
	public static final String PK_CORP = "pk_corp";
	public static final String VOTHERCODE = "vothercode";
	public static final String VOTHERNAME = "vothername";
	public static final String VOTHERBIZ = "votherbiz";
	public static final String PK_DEBITSUBJ = "pk_debitsubj";
	public static final String PK_CREDITSUBJ = "pk_creditsubj";
	public static final String BMERGESAME = "bmergesame";
	public static final String VMEMO = "vmemo";
	public static final String OBJ_ID = "obj_id";
	public static final String CURRENCY = "currency";
			
	/**
	 * 属性pk_subjmap的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getPk_subjmap () {
		return pk_subjmap;
	}   
	/**
	 * 属性pk_subjmap的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newPk_subjmap java.lang.String
	 */
	public void setPk_subjmap (java.lang.String newPk_subjmap ) {
	 	this.pk_subjmap = newPk_subjmap;
	} 	  
	/**
	 * 属性pk_subjbiz的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getPk_subjbiz () {
		return pk_subjbiz;
	}   
	/**
	 * 属性pk_subjbiz的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newPk_subjbiz java.lang.String
	 */
	public void setPk_subjbiz (java.lang.String newPk_subjbiz ) {
	 	this.pk_subjbiz = newPk_subjbiz;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newPk_corp java.lang.String
	 */
	public void setPk_corp (java.lang.String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vothercode的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getVothercode () {
		return vothercode;
	}   
	/**
	 * 属性vothercode的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newVothercode java.lang.String
	 */
	public void setVothercode (java.lang.String newVothercode ) {
	 	this.vothercode = newVothercode;
	} 	  
	/**
	 * 属性vothername的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getVothername () {
		return vothername;
	}   
	/**
	 * 属性vothername的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newVothername java.lang.String
	 */
	public void setVothername (java.lang.String newVothername ) {
	 	this.vothername = newVothername;
	} 	  
	/**
	 * 属性votherbiz的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getVotherbiz () {
		return votherbiz;
	}   
	/**
	 * 属性votherbiz的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newVotherbiz java.lang.String
	 */
	public void setVotherbiz (java.lang.String newVotherbiz ) {
	 	this.votherbiz = newVotherbiz;
	} 	  
	/**
	 * 属性pk_debitsubj的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getPk_debitsubj () {
		return pk_debitsubj;
	}   
	/**
	 * 属性pk_debitsubj的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newPk_debitsubj java.lang.String
	 */
	public void setPk_debitsubj (java.lang.String newPk_debitsubj ) {
	 	this.pk_debitsubj = newPk_debitsubj;
	} 	  
	/**
	 * 属性pk_creditsubj的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getPk_creditsubj () {
		return pk_creditsubj;
	}   
	/**
	 * 属性pk_creditsubj的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newPk_creditsubj java.lang.String
	 */
	public void setPk_creditsubj (java.lang.String newPk_creditsubj ) {
	 	this.pk_creditsubj = newPk_creditsubj;
	} 	  
	/**
	 * 属性bmergesame的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBmergesame () {
		return bmergesame;
	}   
	/**
	 * 属性bmergesame的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newBmergesame nc.vo.pub.lang.UFBoolean
	 */
	public void setBmergesame (nc.vo.pub.lang.UFBoolean newBmergesame ) {
	 	this.bmergesame = newBmergesame;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newVmemo java.lang.String
	 */
	public void setVmemo (java.lang.String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性obj_id的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getObj_id () {
		return obj_id;
	}   
	/**
	 * 属性obj_id的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newObj_id java.lang.Integer
	 */
	public void setObj_id (java.lang.Integer newObj_id ) {
	 	this.obj_id = newObj_id;
	} 	  
	/**
	 * 属性currency的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getCurrency () {
		return currency;
	}   
	/**
	 * 属性currency的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newCurrency java.lang.String
	 */
	public void setCurrency (java.lang.String newCurrency ) {
	 	this.currency = newCurrency;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-04-26 15:13:53
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-04-26 15:13:53
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-04-26 15:13:53
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_subjmap";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-04-26 15:13:53
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "xjjc_bd_subjmap";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-04-26 15:13:53
	  */
     public SubjMapVO() {
		super();	
	}    
} 
