----------------------------------------------------
-- 表结构建立                                     --
----------------------------------------------------

create table XJJC_BD_ACCSUBJBIZTYPE
(
  dr             NUMBER(10) default 0,
  pk_subjbiztype CHAR(20) not null,
  ts             CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  vcode          VARCHAR2(50),
  vname          VARCHAR2(50)
)
;
alter table XJJC_BD_ACCSUBJBIZTYPE
  add constraint PK_XJJC_BD_ACCSUBJBIZTYPE primary key (PK_SUBJBIZTYPE);

create table XJJC_BD_FREEVALUEMAP
(
  dr               NUMBER(10) default 0,
  pk_bdinfo        CHAR(20),
  pk_corp          CHAR(4),
  pk_freevalue     CHAR(20),
  pk_freevaluemap  CHAR(20) not null,
  pk_usedfreevalue CHAR(20),
  ts               CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  vmemo            VARCHAR2(512),
  votherbiz        VARCHAR2(50),
  vothercode       VARCHAR2(50),
  vothername       VARCHAR2(100),
  obj_id           NUMBER(38)
)
;
alter table XJJC_BD_FREEVALUEMAP
  add constraint PK_XJJC_BD_FREEVALUEMAP primary key (PK_FREEVALUEMAP);

create table XJJC_BD_SUBJMAP
(
  bmergesame     CHAR(1),
  currency       CHAR(1),
  dr             NUMBER(10) default 0,
  obj_id         NUMBER(38),
  pk_corp        CHAR(4),
  pk_creditsubj  CHAR(20),
  pk_debitsubj   CHAR(20),
  pk_subjbiz     CHAR(20),
  pk_subjmap     CHAR(20) not null,
  ts             CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  vmemo          VARCHAR2(512),
  votherbiz      VARCHAR2(50),
  vothercode     VARCHAR2(50),
  vothername     VARCHAR2(100),
  pk_advancesubj CHAR(20),
  pk_suspendsubj CHAR(20)
)
;
alter table XJJC_BD_SUBJMAP
  add constraint PK_XJJC_BD_SUBJMAP primary key (PK_SUBJMAP);

create table XJJC_BD_USEDFREEVALUE
(
  dr               NUMBER(10) default 0,
  pk_bdinfo        CHAR(20),
  pk_corp          CHAR(4),
  pk_needfreevalue CHAR(20) not null,
  ts               CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  vcode            VARCHAR2(50),
  vname            VARCHAR2(50)
)
;
alter table XJJC_BD_USEDFREEVALUE
  add constraint PK_XJJC_BD_USEDFREEVALUE primary key (PK_NEEDFREEVALUE);

create table XJJC_CODE_TO_CODE
(
  othercode VARCHAR2(100),
  nccode    VARCHAR2(100),
  type      VARCHAR2(50),
  nccode2   VARCHAR2(50),
  nccode3   VARCHAR2(50),
  nccode4   VARCHAR2(50)
)
;

create table XJJC_GL_FAKEVOUCHER
(
  dr           NUMBER(10) default 0,
  pk_voucher   CHAR(20) not null,
  pk_vouinvo   CHAR(20) not null,
  ts           CHAR(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
  vinvoname    VARCHAR2(200) not null,
  pk_corp      CHAR(20),
  vinvocode    VARCHAR2(50),
  ninvoamount  NUMBER(28,8),
  obj_id       NUMBER(38),
  vinvoaircorp VARCHAR2(50),
  vinvoairport VARCHAR2(50),
  vinvoperiod  VARCHAR2(50)
)
;
alter table XJJC_GL_FAKEVOUCHER
  add constraint PK_XJJC_GL_FAKEVOUCHER primary key (PK_VOUINVO);

----------------------------------------------------
-- 初始化表基本数据                               --
----------------------------------------------------
--辅助项目
insert into XJJC_BD_USEDFREEVALUE (DR, PK_BDINFO, PK_CORP, PK_NEEDFREEVALUE, TS, VCODE, VNAME)
values (0, '00010000000000000073', '0001', 'XJJC0000000000000004', '2013-04-28 08:54:52', '01', '客户');

insert into XJJC_BD_USEDFREEVALUE (DR, PK_BDINFO, PK_CORP, PK_NEEDFREEVALUE, TS, VCODE, VNAME)
values (0, '0001A11000000000022E', '0001', 'XJJC0000000000000003', '2013-04-27 12:39:30', '04', '车型');

insert into XJJC_BD_USEDFREEVALUE (DR, PK_BDINFO, PK_CORP, PK_NEEDFREEVALUE, TS, VCODE, VNAME)
values (0, '00010000000000000002', '0001', 'XJJC0000000000000002', '2013-04-27 12:39:30', '02', '部门');

insert into XJJC_BD_USEDFREEVALUE (DR, PK_BDINFO, PK_CORP, PK_NEEDFREEVALUE, TS, VCODE, VNAME)
values (0, '00010000000000000073', '0001', 'XJJC0000000000000001', '2013-04-27 12:39:30', '03', '航空公司');

--初始化要进行对照科目的凭证类别
insert into XJJC_BD_ACCSUBJBIZTYPE (DR, PK_SUBJBIZTYPE, TS, VCODE, VNAME)
values (0, 'XJJC0000000000000005', '2013-04-29 19:34:07', '01', '起降费转账凭证');

insert into XJJC_BD_ACCSUBJBIZTYPE (DR, PK_SUBJBIZTYPE, TS, VCODE, VNAME)
values (0, 'XJJC0000000000000006', '2013-04-29 19:34:07', '0101', '起降费');

insert into XJJC_BD_ACCSUBJBIZTYPE (DR, PK_SUBJBIZTYPE, TS, VCODE, VNAME)
values (0, 'XJJC0000000000000008', '2013-04-29 19:34:07', '02', '租赁收入凭证');

insert into XJJC_BD_ACCSUBJBIZTYPE (DR, PK_SUBJBIZTYPE, TS, VCODE, VNAME)
values (0, 'XJJC0000000000000009', '2013-04-29 19:34:07', '0201', '租赁收入');

----------------------------------------------------
-- 功能注册                                       --
----------------------------------------------------

insert into sm_funcregister (CFUNID, CLASS_NAME, DISP_CODE, DR, DS_NAME, FORBID_FLAG, FUN_CODE, FUN_DESC, FUN_LEVEL, FUN_NAME, FUN_PROPERTY, GROUP_FLAG, HELP_NAME, ISBUTTONPOWER, ISHASPARA, ISNEEDBUTTONLOG, KEYFUNC, MODULETYPE, ORGTYPECODE, PARENT_ID, PK_CORP, RESID, SHORTCUTCODE, SUBSYSTEM_ID, SYSTEM_FLAG, TS) values ('0001AA10000000000SJW', 'nc.ui.xjjc.voucher.SubjAssMap', '00030916', null, null, 0, '10081831', null, 4, '收入系统辅助项对照', 0, 4, null, 'N', 'N', 'N', null, 'N', '1', '00016577037063574991', null, null, null, '00018630389491589710', 1, '2013-04-27 12:08:52');
insert into sm_funcregister (CFUNID, CLASS_NAME, DISP_CODE, DR, DS_NAME, FORBID_FLAG, FUN_CODE, FUN_DESC, FUN_LEVEL, FUN_NAME, FUN_PROPERTY, GROUP_FLAG, HELP_NAME, ISBUTTONPOWER, ISHASPARA, ISNEEDBUTTONLOG, KEYFUNC, MODULETYPE, ORGTYPECODE, PARENT_ID, PK_CORP, RESID, SHORTCUTCODE, SUBSYSTEM_ID, SYSTEM_FLAG, TS) values ('0001AA10000000000SJX', 'nc.ui.xjjc.voucher.AccSubjMap', '00030917', null, null, 0, '10081832', null, 4, '收入系统科目对照', 0, 4, null, 'N', 'N', 'N', null, 'N', '1', '00016577037063574991', null, null, null, '00018630389491589710', 1, '2013-04-27 12:08:52');
insert into sm_funcregister (CFUNID, CLASS_NAME, DISP_CODE, DR, DS_NAME, FORBID_FLAG, FUN_CODE, FUN_DESC, FUN_LEVEL, FUN_NAME, FUN_PROPERTY, GROUP_FLAG, HELP_NAME, ISBUTTONPOWER, ISHASPARA, ISNEEDBUTTONLOG, KEYFUNC, MODULETYPE, ORGTYPECODE, PARENT_ID, PK_CORP, RESID, SHORTCUTCODE, SUBSYSTEM_ID, SYSTEM_FLAG, TS) values ('0001AA10000000004Y8Q', 'nc.ui.xjjc.voucher.AirIncomeVoucher', '01000107', null, null, 0, '20021070', null, 4, '接口凭证管理', 0, 4, null, 'N', 'N', 'N', null, 'N', '1', '00016678656594395151', null, null, null, '00016579518875021027', 1, '2013-04-30 16:07:03');

----------------------------------------------------
-- 单据模板                                       --
----------------------------------------------------

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DR, METADATACLASS, MODEL_TYPE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('辅助项对照', 'SYSTEM', 0, 'freevalue_map.freevaluemap', null, null, null, '0001AA10000000000VN0', '10081831', '@@@@', null, 'N', '2013-04-28 18:27:35', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DR, METADATACLASS, MODEL_TYPE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('科目对照', 'SYSTEM', 0, 'accsubj_map.subjmap', null, null, null, '0001AA10000000004S2K', '10081832', '@@@@', null, 'N', '2013-05-07 08:37:05', null);

insert into pub_billtemplet (BILL_TEMPLETCAPTION, BILL_TEMPLETNAME, DR, METADATACLASS, MODEL_TYPE, NODECODE, OPTIONS, PK_BILLTEMPLET, PK_BILLTYPECODE, PK_CORP, RESID, SHAREFLAG, TS, VALIDATEFORMULA)
values ('航空收入凭证', 'SYSTEM', 0, 'voucherbackup.voucherbackup', null, null, null, '0001AA10000000004Y8Y', '20021070', '@@@@', null, 'N', '2013-05-03 17:54:33', null);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 5, '外系统名称', null, 0, 1, null, -1, null, 50, 'fakeobj_id', 0, 'N', 1, 'N', null, 0, null, null, null, 'N', 1, null, '0001AA10000000000VN0', '1022AA1000000000LLS2', '@@@@', 0, '人员基本档案', null, null, 'N', 1, 7, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 1, '外系统PK', null, 0, 0, null, -1, null, 20, 'obj_id', 0, 'N', 1, 'N', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '1022AA1000000000LK8I', '@@@@', 0, null, null, null, 'N', 0, 9, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '辅助项类别', null, 0, 0, null, -1, null, 20, 'pk_usedfreevalue', 0, 'N', 1, 'N', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000Y1E', '@@@@', 0, null, null, null, 'N', 0, 3, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 5, '辅助项名称', null, 0, 1, null, -1, 'pk_freevalue', 50, 'pk_freevalue', null, 'N', 1, 'N', null, 0, null, null, null, 'N', 1, null, '0001AA10000000000VN0', '1002AA100000000004V7', null, 0, '客商档案', null, null, 'N', 1, 12, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '外系统编码', null, 0, 0, null, -1, null, 20, 'vothercode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '1022AA1000000000LIOY', null, 0, null, null, null, 'N', 1, 5, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '外系统名称', null, 0, 0, null, -1, null, 50, 'vothername', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '1022AA1000000000LJGR', null, 0, null, null, null, 'N', 0, 6, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_freevaluemap', null, 'N', 1, 'N', null, 0, 'pk_freevaluemap', 'freevalue_map.freevaluemap.pk_freevaluemap', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN3', null, 0, null, null, null, 'N', 0, 1, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'ts', null, 'N', 1, 'Y', null, 0, 'ts', 'freevalue_map.freevaluemap.ts', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN4', null, 0, null, null, null, 'N', 1, 14, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_bdinfo', null, 'N', 1, 'N', null, 0, 'pk_bdinfo', 'freevalue_map.freevaluemap.pk_bdinfo', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN5', null, 0, null, null, null, 'N', 0, 4, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 1, null, -1, null, -1, 'vmemo', null, 'N', 1, 'N', null, 0, 'vmemo', 'freevalue_map.freevaluemap.vmemo', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN6', null, 0, null, null, null, 'N', 1, 13, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 10);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_corp', null, 'N', 1, 'N', null, 0, 'pk_corp', 'freevalue_map.freevaluemap.pk_corp', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN7', null, 0, null, null, null, 'N', 0, 2, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'votherbiz', null, 'N', 1, 'Y', null, 0, 'votherbiz', 'freevalue_map.freevaluemap.votherbiz', null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000VN8', null, 0, null, null, null, 'N', 1, 8, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '辅助项名称', null, 0, 0, null, -1, 'pk_freevalue', 50, 'freevaluename', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000YQ4', null, 0, null, null, null, 'N', 0, 11, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '辅助项编码', null, 0, 0, null, -1, null, 20, 'freevaluecode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000000VN0', '0001AA10000000000YQ3', null, 0, null, null, null, 'N', 1, 10, 'freevaluemap', '辅助项对照', 0, '2013-04-28 18:27:35', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '外系统业务类型', null, 0, 0, null, -1, null, 20, 'pk_subjbiz', 0, 'N', 1, 'N', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '1022AA1000000000LOV7', '@@@@', 0, null, null, null, 'N', 0, 24, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '预收科目编码', null, 0, 0, null, -1, null, 20, 'advancesubjcode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '1022ZF1000000000ML9U', null, 0, null, null, null, 'N', 1, 18, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '挂应收科目编码', null, 0, 0, null, -1, null, 20, 'suspendsubjcode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '1022ZF1000000000ML9V', null, 0, null, null, null, 'N', 1, 15, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '挂应收科目名称', null, 0, 0, null, -1, null, 20, 'suspendsubjname', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '1022ZF1000000000ML9W', null, 0, null, null, null, 'N', 0, 16, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '预收科目名称', null, 0, 0, null, -1, null, 20, 'advancesubjname', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '1022ZF1000000000ML9Y', null, 0, null, null, null, 'N', 0, 19, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, '挂应收科目名称', null, 0, 1, 'suspendsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_suspendsubj);suspendsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_suspendsubj)', -1, null, -1, 'pk_suspendsubj', null, 'N', 1, 'N', 'suspendsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_suspendsubj);suspendsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_suspendsubj)', 0, 'pk_suspendsubj', 'accsubj_map.subjmap.pk_suspendsubj', null, 'N', 1, null, '0001AA10000000004S2K', '1022ZF1000000000ML9X', null, 0, null, null, null, 'N', 1, 17, 'subjmap', 'subjmap', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, '预收科目名称', null, 0, 1, 'advancesubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_advancesubj);advancesubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_advancesubj)', -1, null, -1, 'pk_advancesubj', null, 'N', 1, 'N', 'advancesubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_advancesubj);advancesubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_advancesubj)', 0, 'pk_advancesubj', 'accsubj_map.subjmap.pk_advancesubj', null, 'N', 1, null, '0001AA10000000004S2K', '1022ZF1000000000ML9Z', null, 0, null, null, null, 'N', 1, 20, 'subjmap', 'subjmap', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '借方科目名称', null, 0, 0, null, -1, null, 100, 'debitsubjname', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2M', null, 0, null, null, null, 'N', 0, 10, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '贷方科目名称', null, 0, 0, null, -1, null, 100, 'creditsubjname', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2S', null, 0, null, null, null, 'N', 0, 13, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 5, '外系统名称', null, 0, 1, null, -1, null, 20, 'fakeobj_id', null, 'N', 1, 'N', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004S2K', '0001AA10000000004S2U', null, 0, '人员基本档案', null, null, 'N', 1, 5, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '借方科目编码', null, 0, 0, null, -1, null, 20, 'debitsubjcode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2W', null, 0, null, null, null, 'N', 1, 9, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '贷方科目编码', null, 0, 0, null, -1, null, 20, 'creditsubjcode', null, 'N', 1, 'Y', null, 0, null, null, null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2Z', null, 0, null, null, null, 'N', 1, 12, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, 'false', 0, 1, null, -1, null, -1, 'bmergesame', null, 'N', 1, 'Y', null, 0, 'bmergesame', 'accsubj_map.subjmap.bmergesame', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2P', null, 0, null, null, null, 'N', 1, 21, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'ts', null, 'N', 1, 'N', null, 0, 'ts', 'accsubj_map.subjmap.ts', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2L', null, 0, null, null, null, 'N', 0, 23, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, '借方科目名称', null, 0, 1, 'creditsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_creditsubj);creditsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_creditsubj)', -1, null, 100, 'pk_debitsubj', null, 'N', 1, 'N', 'creditsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_creditsubj);creditsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_creditsubj)', 0, 'pk_debitsubj', 'accsubj_map.subjmap.pk_debitsubj', null, 'N', 1, null, '0001AA10000000004S2K', '0001AA10000000004S2N', null, 0, null, null, null, 'N', 1, 11, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'votherbiz', null, 'N', 1, 'Y', null, 0, 'votherbiz', 'accsubj_map.subjmap.votherbiz', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2O', null, 0, null, null, null, 'N', 1, 6, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_subjmap', null, 'N', 1, 'N', null, 0, 'pk_subjmap', 'accsubj_map.subjmap.pk_subjmap', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2Q', null, 0, null, null, null, 'N', 0, 1, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'currency', null, 'N', 1, 'N', null, 0, 'currency', 'accsubj_map.subjmap.currency', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2T', null, 0, null, null, null, 'N', 0, 8, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, '贷方科目名称', null, 0, 1, 'debitsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_debitsubj);debitsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_debitsubj)', -1, null, 100, 'pk_creditsubj', null, 'N', 1, 'N', 'debitsubjcode->getColValue(bd_accsubj, subjcode, pk_accsubj, pk_debitsubj);debitsubjname->getColValue(bd_accsubj, subjname, pk_accsubj, pk_debitsubj)', 0, 'pk_creditsubj', 'accsubj_map.subjmap.pk_creditsubj', null, 'N', 1, null, '0001AA10000000004S2K', '0001AA10000000004S2V', null, 0, null, null, null, 'N', 1, 14, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'vothercode', null, 'N', 1, 'Y', null, 0, 'vothercode', 'accsubj_map.subjmap.vothercode', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2X', null, 0, null, null, null, 'N', 1, 3, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_corp', null, 'N', 1, 'N', null, 0, 'pk_corp', 'accsubj_map.subjmap.pk_corp', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S2Y', null, 0, null, null, null, 'N', 0, 2, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'obj_id', null, 'N', 1, 'N', null, 0, 'obj_id', 'accsubj_map.subjmap.obj_id', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S30', null, 0, null, null, null, 'N', 0, 7, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 1, null, -1, null, -1, 'vmemo', null, 'N', 1, 'Y', null, 0, 'vmemo', 'accsubj_map.subjmap.vmemo', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S31', null, 0, null, null, null, 'N', 1, 22, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 5);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'vothername', null, 'N', 1, 'Y', null, 0, 'vothername', 'accsubj_map.subjmap.vothername', null, 'N', 0, null, '0001AA10000000004S2K', '0001AA10000000004S32', null, 0, null, null, null, 'N', 0, 4, 'subjmap', '科目对照', 0, '2013-05-07 08:37:05', 'N', null, null, null, 1, 1, 'N', 1, null, 3);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '发票名称', null, 0, 1, null, -1, null, 100, 'vinvoname', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004Y8Y', '1022AA1000000000M85T', '@@@@', 0, null, null, null, 'N', 1, 2, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 4);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '发票期间', null, 0, 1, null, -1, null, 20, 'vinvoperiod', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004Y8Y', '1022AA1000000000M9P6', '@@@@', 0, null, null, null, 'N', 1, 3, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '航空公司', null, 0, 1, null, -1, null, 20, 'vinvoaircorp', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004Y8Y', '1022AA1000000000M9P7', '@@@@', 0, null, null, null, 'N', 1, 5, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, '机场', null, 0, 1, null, -1, null, 20, 'vinvoairport', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004Y8Y', '1022AA1000000000M9P8', '@@@@', 0, null, null, null, 'N', 1, 6, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 2, '发票金额', null, 0, 1, null, -1, null, 20, 'ninvoamount', 0, 'N', 1, 'Y', null, 0, null, null, null, 'N', 1, null, '0001AA10000000004Y8Y', '1022AA1000000000M9P9', '@@@@', 0, '2', null, null, 'N', 1, 4, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, '制单人', null, 0, 0, null, -1, 'pk_prepared', -1, 'user_name', null, 'N', 1, 'Y', null, 0, 'user_name', 'user.User.user_name', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y95', null, 0, null, null, null, 'N', 1, 11, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'year', null, 'N', 1, 'Y', null, 0, 'year', 'voucherbackup.voucherbackup.year', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y90', null, 0, null, null, null, 'N', 1, 8, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'totaldebit', null, 'N', 1, 'Y', null, 0, 'totaldebit', 'voucherbackup.voucherbackup.totaldebit', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y91', null, 0, null, null, null, 'N', 1, 12, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'pk_voucher', null, 'N', 1, 'N', 'explanation->getColValue(gl_voucher, explanation, pk_voucher, pk_voucher);no->getColValue(gl_voucher, no, pk_voucher, pk_voucher);period->getColValue(gl_voucher, period, pk_voucher, pk_voucher);prepareddate->getColValue(gl_voucher, prepareddate, pk_voucher, pk_voucher);totalcredit->getColValue(gl_voucher, totalcredit, pk_voucher, pk_voucher);totaldebit->getColValue(gl_voucher, totaldebit, pk_voucher, pk_voucher);year->getColValue(gl_voucher, "year", pk_voucher, pk_voucher);pk_prepared->getColValue(gl_voucher, pk_prepared, pk_voucher, pk_voucher);user_name->getColValue(sm_user, user_name, cuserid, pk_prepared);', 0, 'pk_voucher', 'voucherbackup.voucherbackup.pk_voucher', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y92', null, 0, null, null, null, 'N', 0, 1, 'pk_voucher', '凭证主键', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'period', null, 'N', 1, 'Y', null, 0, 'period', 'voucherbackup.voucherbackup.period', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y93', null, 0, null, null, null, 'N', 1, 9, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'prepareddate', null, 'N', 1, 'Y', null, 0, 'prepareddate', 'voucherbackup.voucherbackup.prepareddate', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y94', null, 0, null, null, null, 'N', 1, 10, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'no', null, 'N', 1, 'Y', null, 0, 'no', 'voucherbackup.voucherbackup.no', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y96', null, 0, null, null, null, 'N', 1, 7, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'explanation', null, 'N', 1, 'Y', null, 0, 'explanation', 'voucherbackup.voucherbackup.explanation', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y97', null, 0, null, null, null, 'N', 1, 14, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 4);

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, -1, null, null, 0, 0, null, -1, null, -1, 'totalcredit', null, 'N', 1, 'Y', null, 0, 'totalcredit', 'voucherbackup.voucherbackup.totalcredit', null, 'N', 0, null, '0001AA10000000004Y8Y', '0001AA10000000004Y98', null, 0, null, null, null, 'N', 1, 13, 'pk_voucher', 'pk_voucher', 0, '2013-05-03 17:54:33', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

insert into pub_billtemplet_t (BASETAB, DR, METADATACLASS, METADATAPATH, MIXINDEX, PK_BILLTEMPLET, PK_BILLTEMPLET_T, POS, POSITION, RESID, TABCODE, TABINDEX, TABNAME, TS, VDEF1, VDEF2, VDEF3)
values (null, 0, 'freevalue_map.freevaluemap', null, null, '0001AA10000000000VN0', '1022AA1000000000LMJZ', 0, 0, null, 'freevaluemap', 0, '辅助项对照', '2013-04-28 18:27:35', null, null, null);

insert into pub_billtemplet_t (BASETAB, DR, METADATACLASS, METADATAPATH, MIXINDEX, PK_BILLTEMPLET, PK_BILLTEMPLET_T, POS, POSITION, RESID, TABCODE, TABINDEX, TABNAME, TS, VDEF1, VDEF2, VDEF3)
values (null, 0, 'accsubj_map.subjmap', null, null, '0001AA10000000004S2K', '1022ZF1000000000MLA1', 0, 0, null, 'subjmap', 0, '科目对照', '2013-05-07 08:37:05', null, null, null);

insert into pub_billtemplet_t (BASETAB, DR, METADATACLASS, METADATAPATH, MIXINDEX, PK_BILLTEMPLET, PK_BILLTEMPLET_T, POS, POSITION, RESID, TABCODE, TABINDEX, TABNAME, TS, VDEF1, VDEF2, VDEF3)
values (null, 0, 'voucherbackup.voucherbackup', null, null, '0001AA10000000004Y8Y', '1022AA1000000000MAHJ', 0, 0, null, 'pk_voucher', 0, '凭证主键', '2013-05-03 17:54:33', null, null, null);

----------------------------------------------------
-- 查询模板                                       --
----------------------------------------------------

insert into pub_query_templet (DESCRIBE, DR, FIXCONDITION, ID, METACLASS, MODEL_CODE, MODEL_NAME, NODE_CODE, PK_CORP, RESID, TS)
values (null, 0, null, '0001AA10000000005FZN', 'bca89e45-4d30-4bec-981e-56a1d52ed720', '20021070', '航空收入凭证', '20021070', '@@@@', null, '2013-05-03 17:01:09');

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 0, 0, null, 0, 'vinvoairport', '机场', null, '0001AA10000000005FZO', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 1, 0, null, 0, 'vinvoaircorp', '航空公司', null, '0001AA10000000005FZP', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 2, 0, null, 0, 'vinvoperiod', '发票期间', null, '0001AA10000000005FZQ', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 3, 0, null, 0, 'vinvoname', '发票名称', null, '0001AA10000000005FZR', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 4, 0, null, 0, 'pk_voucher.year', '凭证.会计年度', null, '0001AA10000000005FZS', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 0, 5, 0, null, 0, 'pk_voucher.period', '凭证.会计期间', null, '0001AA10000000005FZT', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'like@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 1, 6, 0, null, 0, 'pk_voucher.no', '凭证.凭证编码', null, '0001AA10000000005FZU', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'between@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '-99', 3, 7, 0, null, 0, 'pk_voucher.prepareddate', '凭证.制单日期', null, '0001AA10000000005FZV', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, 'between@=@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

insert into pub_query_condition (ADDISNULL4POWER, CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MUST, IF_ORDER, IF_SUM, IF_USED, INSTRUMENTSQL, ISCONDITION, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('N', '操作员', 5, 8, 0, null, 0, 'pk_voucher.pk_prepared', '凭证.制单人', null, '0001AA10000000005FZW', 'Y', 'N', 'Y', null, 'N', 'N', 'N', 'N', 'N', 'Y', null, 'Y', null, '=@between@like@>@>=@<@<=@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '0001AA10000000005FZN', null, null, 2, null, null, '2013-05-03 17:01:09', null, null);

