/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.xjjc.freevaluemap;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-04-26 13:38:19
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AssValueMapVO extends SuperVO {
	private java.lang.String pk_freevaluemap;
	private java.lang.String pk_corp;
	private java.lang.String pk_usedfreevalue;
	private java.lang.String pk_bdinfo;
	private java.lang.Integer obj_id;
	private java.lang.String vothercode;
	private java.lang.String vothername;
	private java.lang.String votherbiz;
	private java.lang.String pk_freevalue;
	private java.lang.String vmemo;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FREEVALUEMAP = "pk_freevaluemap";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_USEDFREEVALUE = "pk_usedfreevalue";
	public static final String PK_BDINFO = "pk_bdinfo";
	public static final String OBJ_ID = "obj_id";
	public static final String VOTHERCODE = "vothercode";
	public static final String VOTHERNAME = "vothername";
	public static final String VOTHERBIZ = "votherbiz";
	public static final String PK_FREEVALUE = "pk_freevalue";
	public static final String VMEMO = "vmemo";
			
	/**
	 * 属性pk_freevaluemap的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_freevaluemap () {
		return pk_freevaluemap;
	}   
	/**
	 * 属性pk_freevaluemap的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newPk_freevaluemap java.lang.String
	 */
	public void setPk_freevaluemap (java.lang.String newPk_freevaluemap ) {
	 	this.pk_freevaluemap = newPk_freevaluemap;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newPk_corp java.lang.String
	 */
	public void setPk_corp (java.lang.String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性pk_usedfreevalue的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_usedfreevalue () {
		return pk_usedfreevalue;
	}   
	/**
	 * 属性pk_usedfreevalue的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newPk_usedfreevalue java.lang.String
	 */
	public void setPk_usedfreevalue (java.lang.String newPk_usedfreevalue ) {
	 	this.pk_usedfreevalue = newPk_usedfreevalue;
	} 	  
	/**
	 * 属性pk_bdinfo的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bdinfo () {
		return pk_bdinfo;
	}   
	/**
	 * 属性pk_bdinfo的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newPk_bdinfo java.lang.String
	 */
	public void setPk_bdinfo (java.lang.String newPk_bdinfo ) {
	 	this.pk_bdinfo = newPk_bdinfo;
	} 	  
	/**
	 * 属性obj_id的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getObj_id () {
		return obj_id;
	}   
	/**
	 * 属性obj_id的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newObj_id java.lang.Integer
	 */
	public void setObj_id (java.lang.Integer newObj_id ) {
	 	this.obj_id = newObj_id;
	} 	  
	/**
	 * 属性vothercode的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getVothercode () {
		return vothercode;
	}   
	/**
	 * 属性vothercode的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newVothercode java.lang.String
	 */
	public void setVothercode (java.lang.String newVothercode ) {
	 	this.vothercode = newVothercode;
	} 	  
	/**
	 * 属性vothername的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getVothername () {
		return vothername;
	}   
	/**
	 * 属性vothername的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newVothername java.lang.String
	 */
	public void setVothername (java.lang.String newVothername ) {
	 	this.vothername = newVothername;
	} 	  
	/**
	 * 属性votherbiz的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getVotherbiz () {
		return votherbiz;
	}   
	/**
	 * 属性votherbiz的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newVotherbiz java.lang.String
	 */
	public void setVotherbiz (java.lang.String newVotherbiz ) {
	 	this.votherbiz = newVotherbiz;
	} 	  
	/**
	 * 属性pk_freevalue的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_freevalue () {
		return pk_freevalue;
	}   
	/**
	 * 属性pk_freevalue的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newPk_freevalue java.lang.String
	 */
	public void setPk_freevalue (java.lang.String newPk_freevalue ) {
	 	this.pk_freevalue = newPk_freevalue;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newVmemo java.lang.String
	 */
	public void setVmemo (java.lang.String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-04-26 13:38:19
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-04-26 13:38:19
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-04-26 13:38:19
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_freevaluemap";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-04-26 13:38:19
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "xjjc_bd_freevaluemap";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-04-26 13:38:19
	  */
     public AssValueMapVO() {
		super();	
	}    
} 
