/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.xjjc.freevaluemap;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-04-26 13:11:02
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class UsedFreeValueVO extends SuperVO {
	private java.lang.String pk_needfreevalue;
	private java.lang.String pk_corp;
	private java.lang.String vcode;
	private java.lang.String vname;
	private java.lang.String pk_bdinfo;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_NEEDFREEVALUE = "pk_needfreevalue";
	public static final String PK_CORP = "pk_corp";
	public static final String VCODE = "vcode";
	public static final String VNAME = "vname";
	public static final String PK_BDINFO = "pk_bdinfo";
			
	/**
	 * 属性pk_needfreevalue的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getPk_needfreevalue () {
		return pk_needfreevalue;
	}   
	/**
	 * 属性pk_needfreevalue的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newPk_needfreevalue java.lang.String
	 */
	public void setPk_needfreevalue (java.lang.String newPk_needfreevalue ) {
	 	this.pk_needfreevalue = newPk_needfreevalue;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newPk_corp java.lang.String
	 */
	public void setPk_corp (java.lang.String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vcode的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getVcode () {
		return vcode;
	}   
	/**
	 * 属性vcode的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newVcode java.lang.String
	 */
	public void setVcode (java.lang.String newVcode ) {
	 	this.vcode = newVcode;
	} 	  
	/**
	 * 属性vname的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getVname () {
		return vname;
	}   
	/**
	 * 属性vname的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newVname java.lang.String
	 */
	public void setVname (java.lang.String newVname ) {
	 	this.vname = newVname;
	} 	  
	/**
	 * 属性pk_bdinfo的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getPk_bdinfo () {
		return pk_bdinfo;
	}   
	/**
	 * 属性pk_bdinfo的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newPk_bdinfo java.lang.String
	 */
	public void setPk_bdinfo (java.lang.String newPk_bdinfo ) {
	 	this.pk_bdinfo = newPk_bdinfo;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-04-26 13:11:02
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-04-26 13:11:02
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-04-26 13:11:02
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_needfreevalue";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-04-26 13:11:02
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "xjjc_bd_usedfreevalue";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-04-26 13:11:02
	  */
     public UsedFreeValueVO() {
		super();	
	}    
} 
