/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.xjjc.voucher;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-05-03 11:29:52
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class FakeVoucherVO extends SuperVO {
	private java.lang.String pk_vouinvo;
	private java.lang.String pk_voucher;
	private java.lang.String vinvoname;
	private java.lang.String vinvocode;
	private java.lang.String pk_corp;
	private java.lang.Integer obj_id;
	private java.lang.String vinvoperiod;
	private nc.vo.pub.lang.UFDouble ninvoamount;
	private java.lang.String vinvoaircorp;
	private java.lang.String vinvoairport;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_VOUINVO = "pk_vouinvo";
	public static final String PK_VOUCHER = "pk_voucher";
	public static final String VINVONAME = "vinvoname";
	public static final String VINVOCODE = "vinvocode";
	public static final String PK_CORP = "pk_corp";
	public static final String OBJ_ID = "obj_id";
	public static final String VINVOPERIOD = "vinvoperiod";
	public static final String NINVOAMOUNT = "ninvoamount";
	public static final String VINVOAIRCORP = "vinvoaircorp";
	public static final String VINVOAIRPORT = "vinvoairport";
			
	/**
	 * 属性pk_vouinvo的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getPk_vouinvo () {
		return pk_vouinvo;
	}   
	/**
	 * 属性pk_vouinvo的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newPk_vouinvo java.lang.String
	 */
	public void setPk_vouinvo (java.lang.String newPk_vouinvo ) {
	 	this.pk_vouinvo = newPk_vouinvo;
	} 	  
	/**
	 * 属性pk_voucher的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getPk_voucher () {
		return pk_voucher;
	}   
	/**
	 * 属性pk_voucher的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newPk_voucher java.lang.String
	 */
	public void setPk_voucher (java.lang.String newPk_voucher ) {
	 	this.pk_voucher = newPk_voucher;
	} 	  
	/**
	 * 属性vinvoname的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getVinvoname () {
		return vinvoname;
	}   
	/**
	 * 属性vinvoname的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newVinvoname java.lang.String
	 */
	public void setVinvoname (java.lang.String newVinvoname ) {
	 	this.vinvoname = newVinvoname;
	} 	  
	/**
	 * 属性vinvocode的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getVinvocode () {
		return vinvocode;
	}   
	/**
	 * 属性vinvocode的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newVinvocode java.lang.String
	 */
	public void setVinvocode (java.lang.String newVinvocode ) {
	 	this.vinvocode = newVinvocode;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newPk_corp java.lang.String
	 */
	public void setPk_corp (java.lang.String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性obj_id的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getObj_id () {
		return obj_id;
	}   
	/**
	 * 属性obj_id的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newObj_id java.lang.Integer
	 */
	public void setObj_id (java.lang.Integer newObj_id ) {
	 	this.obj_id = newObj_id;
	} 	  
	/**
	 * 属性vinvoperiod的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getVinvoperiod () {
		return vinvoperiod;
	}   
	/**
	 * 属性vinvoperiod的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newVinvoperiod java.lang.String
	 */
	public void setVinvoperiod (java.lang.String newVinvoperiod ) {
	 	this.vinvoperiod = newVinvoperiod;
	} 	  
	/**
	 * 属性ninvoamount的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNinvoamount () {
		return ninvoamount;
	}   
	/**
	 * 属性ninvoamount的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newNinvoamount nc.vo.pub.lang.UFDouble
	 */
	public void setNinvoamount (nc.vo.pub.lang.UFDouble newNinvoamount ) {
	 	this.ninvoamount = newNinvoamount;
	} 	  
	/**
	 * 属性vinvoaircorp的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getVinvoaircorp () {
		return vinvoaircorp;
	}   
	/**
	 * 属性vinvoaircorp的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newVinvoaircorp java.lang.String
	 */
	public void setVinvoaircorp (java.lang.String newVinvoaircorp ) {
	 	this.vinvoaircorp = newVinvoaircorp;
	} 	  
	/**
	 * 属性vinvoairport的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getVinvoairport () {
		return vinvoairport;
	}   
	/**
	 * 属性vinvoairport的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newVinvoairport java.lang.String
	 */
	public void setVinvoairport (java.lang.String newVinvoairport ) {
	 	this.vinvoairport = newVinvoairport;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-05-03 11:29:52
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-05-03 11:29:52
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-05-03 11:29:52
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_vouinvo";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-05-03 11:29:52
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "xjjc_gl_fakevoucher";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-05-03 11:29:52
	  */
     public FakeVoucherVO() {
		super();	
	}    
} 
